services:
  
  laundrydb:
    image: mongo
  
  laundry.api:
    image: laundry.api
    build:
      context: .
      dockerfile: Services/Laundry/Laundry.API/Dockerfile
  
  
  paymentdb:
    image: mongo
  
  payment.api:
    image: payment.api
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
      
  payment.grpc:
    image: payment.grpc
    build:
      context: .
      dockerfile: Services/Payment/Payment.GRPC/Dockerfile

  identitydb:
    image: mcr.microsoft.com/mssql/server:2017-latest
      
  canteendb:
    image: mongo

  canteencache:
    image: redis:alpine
  
  canteen.api:
    image: canteen.api
    build:
      context: .
      dockerfile: Services/Canteen/Canteen.API/Dockerfile
      
  

volumes:
  mongo_canteen:
  mongo_payment:
  mongo_laundry:
  identity_data:
