version: '3.4'

services:
  laundrydb:
    container_name: laundry
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_laundry:/data/db
  
  laundry.api:
    container_name: laundry.api
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://laundrydb:27017"
    depends_on:
      - laundrydb
    ports:
      - "8000:8080"
      
      
  paymentdb:
    container_name: payment
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_payment:/data/db
  
  payment.api:
    container_name: payment.api
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://paymentdb:27017"
    depends_on:
      - paymentdb
    ports:
      - "8001:8080"
      
  payment.grpc:
    container_name: payment.grpc
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://paymentdb:27017"
    depends_on:
      - paymentdb
    ports:
      - "8004:8080"

  
  
  canteendb:
    container_name: canteen
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo_canteen:/data/db

  canteencache:
    container_name: canteencache
    restart: always
    ports:
      - "6379:6379"
  
  canteen.api:
    container_name: canteen.api
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://canteendb:27017"
      - "CacheSettings:ConnectionString=canteencache:6379"
    depends_on:
      - canteendb
      - canteencache
    ports:
      - "8002:8080"