services:
  
  laundrydb:
    image: mongo
  
  laundry.api:
    image: laundry.api
    build:
      context: .
      dockerfile: Services/Laundry/Laundry.API/Dockerfile
  
  
  paymentdb:
    image: mongo
  
  payment.api:
    image: payment.api
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile

      
  canteendb:
    image: mongo

  canteencache:
    image: redis:alpine
  
  canteen.api:
    image: canteen.api
    build:
      context: .
      dockerfile: Services/Canteen/Canteen.API/Dockerfile

volumes:
  mongo_canteen:
  mongo_payment:
  mongo_laundry:
