services:
  laundrydb:
    container_name: laundry
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_laundry:/data/db
  
  laundry-api:
    container_name: laundry-api
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://laundrydb:27017"
      - "GrpcSettings:PaymentUrl=http://payment-grpc:8080"
    depends_on:
      - laundrydb
      - payment-grpc
    ports:
      - "8000:8080"
      
      
  paymentdb:
    container_name: payment
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_payment:/data/db
  
  payment-api:
    container_name: payment-api
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://paymentdb:27017"
    depends_on:
      - paymentdb
    ports:
      - "8001:8080"
      
  payment-grpc:
    container_name: payment-grpc
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://paymentdb:27017"
    depends_on:
      - paymentdb
    ports:
      - "8004:8080"

  identitydb:
    container_name: identity
    environment:
      - SA_PASSWORD=DormServiceRS2
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identity_data:/var/opt/mssql/data
  
  canteendb:
    container_name: canteen
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo_canteen:/data/db

  canteencache:
    container_name: canteencache
    restart: always
    ports:
      - "6379:6379"
  
  canteen-api:
    container_name: canteen-api
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://canteendb:27017"
      - "CacheSettings:ConnectionString=canteencache:6379"
      - "GrpcSettings:PaymentUrl=http://payment-grpc:8080"
    depends_on:
      - canteendb
      - canteencache
      - payment-grpc
    ports:
      - "8002:8080"

  identityserver:
    container_name: identityserver
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnectionString=Server=identitydb;Database=IdentityDb;User Id=sa;Password=DormServiceRS2;TrustServerCertificate=True;"
    depends_on:
      - identitydb
    ports:
        - "4000:8080"

  documentationdb:
    container_name: documentation
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - mongo_documentation:/data/db
  
  documentation-api:
    container_name: documentation-api
    environment:
      -  ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://documentationdb:27017"
    depends_on:
      - documentationdb
    ports:
      - "8005:8080"
